### ISSUE TITLE
#Botiquette

### ISSUE THREAD

**Issue by aschrijver** [botwiki/botwiki-wp-theme#22]
Great site you run. Just learned about it. Unfortunately I have no time to PR, but on the new `fediverse-ideas` initiative at Codeberg (in the same organization where Fediverse Enhancement Proposals are tracked), I created an issue about Botiquette. While these are mostly guidelines for operating well-behaved bots, some aspects (when elaborating further) may relate to their technical implementation.

https://codeberg.org/fediverse/fediverse-ideas/issues/33

**Comment by stefanbohacek** [comment]
Thank you!

I made a small update to the guide you linked to as outlined [here](https://codeberg.org/fediverse/fediverse-ideas/issues/33#issuecomment-922001). I'll go ahead and close this issue and I'm happy to continue the conversation over there.
